services:
  redis:
    image: redis:latest
    container_name: flash-sale-redis
    ports:
      - '6379:6379'
  postgres-5:
    image: postgres:latest 
    container_name: flash-sale-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flash-sale
    ports:
      - '5437:5432'
    volumes:
      - postgres_data-5:/var/lib/postgresql/data

volumes:
  postgres_data-5:
